version: "3"
services:
  api:
    image: buraczek2828/breadly
    depends_on:
      - postgres
    ports:
      - 8000:8000
    # volumes:
    #   - ./:/usr/src/app:ro
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=kuba123
      - DATABASE_NAME=Breadly
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCES_TOKEN_EXPIRE_MINUTES=3000
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=kuba123
      - POSTGRES_DB=Breadly
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: